### ISSUE TITLE
How would this even work? This was not even tested?

### ISSUE THREAD

**Issue by JunOllyLi** [NXPmicro/sfw#4]
```
void write_image_ok(void)
{
    uint32_t off;
    status_t status;
    uint32_t primask;
    
    sfw_flash_read(REMAP_FLAG_ADDRESS, &s_remap_trailer, 32);
    
    primask = DisableGlobalIRQ();
    status = sfw_flash_erase(FLASH_AREA_IMAGE_1_OFFSET - SECTOR_SIZE, SECTOR_SIZE);
    
    EnableGlobalIRQ(primask);
    
    memset((void *)s_remap_trailer.magic, 0xff, IMAGE_TRAILER_SIZE - 16);

    s_remap_trailer.image_ok = 0xFF;
    s_remap_trailer.pad1[3] = 0x0;
    
    off = REMAP_FLAG_ADDRESS;

    PRINTF("Write OK flag: off = 0x%x\r\n", off);
    
    primask = DisableGlobalIRQ();
    status = sfw_flash_write(off, (void *)&s_remap_trailer, IMAGE_TRAILER_SIZE);
    if (status) 
    {
        return;
    }
    EnableGlobalIRQ(primask);
}
```

So after the first image update, the line `s_remap_trailer.pad1[3] = 0x0;` would actually write the "Update type" flag as zero. And next update comes in, it won't be able to write that byte anymore, since it is zero and the flash sector was not erased before writting. This makes the second update of the image not being able to be verified after the second reboot.

It should be set to 0xFF instead of 0x0, in my opinion.

**Comment by Tim-Wang38** [comment]
Hi @JunOllyLi ,

Thanks for your feedback, this is indeed a bug which may cause the second update can not move to permanent update state.
Remove the line s_remap_trailer.pad1[3] = 0x0 or change the value to 0xFF can fix this issue.
We will update it in next release.

Thanks
